### ISSUE TITLE
Modification Question

### ISSUE THREAD

**Issue by deehill** [ajaycc17/glazeline#1]
Hi Ajay!

Looking over different Landing page apps created with Vite/React, and saw yours.

If you don't mind, I have a question. Your app has an email "form" but I assume it doesn't actually hook to a back server/system for serving up the "confirm" email to a user who submits their data.

Have you created this kind of logic? 

I'm looking for a landing page app that has ability for an Email Harvesting Contact Form, as well as a section/contact form for accepting userData which would tie into a backend/php kind of db/server.

I'm in the US/east coast.

Thoughts/comments

thanks

-bruce
badouglas@gmail.com

**Comment by ajaycc17** [comment]
I have used EmailJS for the contact form here and everything is set up correctly. @ugh-astya has deployed the site and once he adds the credentials for EmailJS in the environment variables, it will start working fine.
